### ISSUE TITLE
Support "hjdebug" in Hotjar initiate function

### ISSUE THREAD

**Issue by ajayvarghese** [olavoparno/react-use-hotjar#5]
**Is your feature request related to a problem? Please describe.**
I think it will be better if hotjar debug feature is included in this library. I don't see any option to enable it. 

**Describe the solution you'd like**
Hotjar provides a debug feature that you can enable in the hotjar script. I think we can add that as a parameter to this [function](https://github.com/olavoparno/react-use-hotjar/blob/2505d6d64c41fc1e65ec43be918d8cf74e576d78/src/dependencies.ts#L51) 
More on Debug Feature [here](https://stackoverflow.com/questions/40528159/debugging-and-tracking-hotjar-data)

**Additional context**
I am just curious why this is excluded in the library. Is there any particular reason?

**Comment by olavoparno** [comment]
Hello there @ajayvarghese thanks for the issue! I will look into it and come back to you but if you do have an extra spare time, please do open a PR with this contribution if you want it faster.

Responding to your curiosity, it is because this library is just a wrapper around hotjar capabilities, I still did not find a solution to expose the whole HOTJAR API so in the meanwhile I have to expose one by one.

Anyway, I will reply with a solution as soon as possible ;)

**Comment by olavoparno** [comment]
it's up in version 1.1.2, @ajayvarghese
